name: lineal-amp
description: |
  Demo amp to see how to approach amp development. It goes through the different
  tools CML has to help Data teams to do MLOps.

author: luis
specification_version: 1.0
prototype_version: 1.0
date: "2023-10-12"

environment_variables:
  cml_api_key:
    default: "cml api key"
    description: >-
      create an api key, that will be use to query the workspace for
      information
  project_name:
    default: "choose the name from this project page"
    description: >-
      project name of this deployment, it will get use to get the model
      id and use it for the UI application
 

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: prepare enviroment
    script: 01-install-deps/general_req.py
    short_summary: create project structure 
    long_summary: creates project structures, and any prepare steps
    kernel: python3
    cpu: 1
    memory: 2