name: Generative AI usecases
description: |
  AMP that show differents types of GenAI usecases

author: luis
specification_version: 1.0
prototype_version: 1.0
date: "2023-10-12"


environment_variables:
  hf_token:
    default: "add me"
    description: >-
      provide your hugging face token to dowload gated models
  secret_key:
    default: "mysecretkey"
    description: >-
      the key will be use to generate auth cookies, un-implemented currently
  algorithm:
    default: "HS256"
    description: >-
      algorithm use to encode JWT
  access_token_expiration_minutes:
    default: 30
    description: >-
      auth cookie default experiation time

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Nvidia GPU

tasks:
  - type: run_session
    name: prepare enviroment
    script: 01-install-deps/general_req.py
    short_summary: create project structure 
    long_summary: creates project structures, and any prepare steps
    kernel: python3
    cpu: 1
    memory: 2